version: "3.8"
services:
  web:
    build: ./app
    command: gunicorn fruit_therapy.wsgi:application --bind 0.0.0.0:8000
    image: 674786836936.dkr.ecr.us-east-1.amazonaws.com/portfolio_django:web
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - DB_NAME=my_fruits_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=myfruitsdb.cjtpb9pqzxt8.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-54-145-155-219.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
